[package]
name = "rustflame"
version = "0.1.0"
authors = ["Zachary Jordan <zijordan@gmail.com>"]
edition = "2018"

[dependencies]
lodepng = {git = "https://github.com/kornelski/lodepng-rust" }
# "2"
rgb = "0.8"
rand = "0.4"
#conrod = "^0"
nom = "4"
